## NLP LAB: Tokenization & Vocabulary Construction

### Part 1 — Word-level using `tf.keras.layers.TextVectorization`: builds vocab, encodes sentences to integer sequences, decodes back, demonstrates OOV with [UNK].

#### Basic Imports

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from collections import Counter

In [17]:
### Check TensrFlow version
print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.19.0


In [18]:
### Define experimental corpus
corpus = [
    "I love natural language processing",
    "I love deep learning and neural networks",
    "NLP is a subfield of artificial intelligence",
    "Tokenization is the first step in NLP pipelines",
    "Transformers revolutionized natural language understanding",
    "Word embeddings capture semantic relationships",
    "Playing basketball and playing football are both sports",
    "The preprocessing step affects model performance significantly",
    "Large language models have billions of parameters",
    "Text data requires special handling compared to numerical data",
    "NLP techniques are used in chatbots and virtual assistants",
    "Sentiment analysis is a common NLP task",
    "Named entity recognition identifies entities in text",
    "Part-of-speech tagging assigns grammatical categories to words",
    "Machine translation converts text from one language to another",
    "Text classification categorizes text into predefined labels",
    "Language models can generate human-like text",
    "Fine-tuning pre-trained models can improve performance on specific tasks",
    "The choice of tokenizer can impact model performance",
    "Subword tokenization helps handle out-of-vocabulary words",
    "Byte pair encoding is a popular subword tokenization method",
    "WordPiece is another subword tokenization technique",
    "Tokenization can be done at the word, subword, or character level",
    "The vocabulary size affects the model's ability to represent language",
    "Stop words are common words that may be removed during preprocessing",
    "Stemming and lemmatization are techniques for reducing words to their base forms",
]

In [19]:
# Check the length of the corpus
print(f"Number of sentences in the corpus: {len(corpus)}")

Number of sentences in the corpus: 26


In [20]:
### Enumerate the corpus
for i, sentence in enumerate(corpus):
    print(f"{i}: {sentence}")

0: I love natural language processing
1: I love deep learning and neural networks
2: NLP is a subfield of artificial intelligence
3: Tokenization is the first step in NLP pipelines
4: Transformers revolutionized natural language understanding
5: Word embeddings capture semantic relationships
6: Playing basketball and playing football are both sports
7: The preprocessing step affects model performance significantly
8: Large language models have billions of parameters
9: Text data requires special handling compared to numerical data
10: NLP techniques are used in chatbots and virtual assistants
11: Sentiment analysis is a common NLP task
12: Named entity recognition identifies entities in text
13: Part-of-speech tagging assigns grammatical categories to words
14: Machine translation converts text from one language to another
15: Text classification categorizes text into predefined labels
16: Language models can generate human-like text
17: Fine-tuning pre-trained models can improve perfo

### PART 1: Word Level Tokenization using TextVectorization in Keras

In [21]:
# Define the TextVectorization layer

# Create a TextVectorization layer that:
# - Converts text to lowercase and strips punctuation
# - Splits text into tokens by whitespace
# - Outputs integer indices for each token
# - Pads/truncates sequences to a fixed length of 12
word_vectorizer = tf.keras.layers.TextVectorization(
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    output_mode='int',
    output_sequence_length=12
)

In [22]:
# Adapt the vectorizer to the corpus
# 'corpus' should be a list of sentences or text samples
# This step builds the vocabulary based on the corpus
word_vectorizer.adapt(corpus)

In [23]:
# Inspect the vocabulary
# Retrieve the vocabulary learned from the corpus
word_vocab = word_vectorizer.get_vocabulary()

# Print vocabulary size and the actual vocabulary list
print(f"\nVocabulary size: {len(word_vocab)}")
print(f"Vocabulary: {word_vocab}")


Vocabulary size: 133
Vocabulary: ['', '[UNK]', 'the', 'text', 'language', 'words', 'tokenization', 'to', 'is', 'subword', 'nlp', 'models', 'can', 'are', 'and', 'performance', 'of', 'in', 'a', 'word', 'techniques', 'step', 'preprocessing', 'playing', 'natural', 'model', 'love', 'i', 'data', 'common', 'be', 'another', 'affects', 'wordpiece', 'vocabulary', 'virtual', 'used', 'understanding', 'translation', 'transformers', 'tokenizer', 'their', 'that', 'technique', 'tasks', 'task', 'tagging', 'subfield', 'stop', 'stemming', 'sports', 'specific', 'special', 'size', 'significantly', 'sentiment', 'semantic', 'revolutionized', 'requires', 'represent', 'removed', 'relationships', 'reducing', 'recognition', 'processing', 'pretrained', 'predefined', 'popular', 'pipelines', 'partofspeech', 'parameters', 'pair', 'outofvocabulary', 'or', 'one', 'on', 'numerical', 'neural', 'networks', 'named', 'method', 'may', 'machine', 'level', 'lemmatization', 'learning', 'large', 'labels', 'into', 'intelligence

In [24]:
# Encode the corpus into integer sequences
# Transform the corpus into sequences of integers
# Each word is replaced by its index in the vocabulary
word_encoded = word_vectorizer(corpus)

print("\nEncoded sequences (sentences X max_len):")
print(word_encoded.numpy())


Encoded sequences (sentences X max_len):
[[ 27  26  24   4  64   0   0   0   0   0   0   0]
 [ 27  26 112  85  14  77  78   0   0   0   0   0]
 [ 10   8  18  47  16 130  89   0   0   0   0   0]
 [  6   8   2 104  21  17  10  68   0   0   0   0]
 [ 39  57  24   4  37   0   0   0   0   0   0   0]
 [ 19 109 121  56  61   0   0   0   0   0   0   0]
 [ 23 125  14  23 103  13 123  50   0   0   0   0]
 [  2  22  21  32  25  15  54   0   0   0   0   0]
 [ 86   4  11  95 124  16  70   0   0   0   0   0]
 [  3  28  58  52  96 114   7  76  28   0   0   0]
 [ 10  20  13  36  17 117  14  35 128   0   0   0]
 [ 55 131   8  18  29  10  45   0   0   0   0   0]
 [ 79 106  63  92 107  17   3   0   0   0   0   0]
 [ 69  46 129  98 120   7   5   0   0   0   0   0]
 [ 82  38 113   3 100  74   4   7  31   0   0   0]
 [  3 115 119   3  88  66  87   0   0   0   0   0]
 [  4  11  12  99  93   3   0   0   0   0   0   0]
 [105  65  11  12  90  15  75  51  44   0   0   0]
 [  2 116  16  40  12  91  25  15   0   

In [25]:
# Decode an encoded sentence back to words
# Create a mapping from index to word
idx2word = {i: w for i, w in enumerate(word_vocab)}
idx2word

{0: '',
 1: '[UNK]',
 2: 'the',
 3: 'text',
 4: 'language',
 5: 'words',
 6: 'tokenization',
 7: 'to',
 8: 'is',
 9: 'subword',
 10: 'nlp',
 11: 'models',
 12: 'can',
 13: 'are',
 14: 'and',
 15: 'performance',
 16: 'of',
 17: 'in',
 18: 'a',
 19: 'word',
 20: 'techniques',
 21: 'step',
 22: 'preprocessing',
 23: 'playing',
 24: 'natural',
 25: 'model',
 26: 'love',
 27: 'i',
 28: 'data',
 29: 'common',
 30: 'be',
 31: 'another',
 32: 'affects',
 33: 'wordpiece',
 34: 'vocabulary',
 35: 'virtual',
 36: 'used',
 37: 'understanding',
 38: 'translation',
 39: 'transformers',
 40: 'tokenizer',
 41: 'their',
 42: 'that',
 43: 'technique',
 44: 'tasks',
 45: 'task',
 46: 'tagging',
 47: 'subfield',
 48: 'stop',
 49: 'stemming',
 50: 'sports',
 51: 'specific',
 52: 'special',
 53: 'size',
 54: 'significantly',
 55: 'sentiment',
 56: 'semantic',
 57: 'revolutionized',
 58: 'requires',
 59: 'represent',
 60: 'removed',
 61: 'relationships',
 62: 'reducing',
 63: 'recognition',
 64: 'processing'

In [26]:
# Decode the first sentence (index 0) by mapping indices back to words
# Skip padding tokens (index 0)
print("\nDecoded sentence 0:")
print(" ".join([idx2word[i] for i in word_encoded[0].numpy() if i != 0]))



Decoded sentence 0:
i love natural language processing


In [27]:
# Test handling of unseen (OOV) words
# Provide a sentence with words not in the training corpus
unseen = ["Unseen vocabulary handling works via unknown tokens"]

print(f"\nOOV Test — '{unseen[0]}'")
print("Encoded:", word_vectorizer(unseen).numpy())
print("→ Token index 1 = [UNK]")  # Index 1 is reserved for unknown words


OOV Test — 'Unseen vocabulary handling works via unknown tokens'
Encoded: [[ 1 34 96  1  1  1  1  0  0  0  0  0]]
→ Token index 1 = [UNK]


### Word Level Tokenization V2

In [28]:
max_vocab_size = 20

word_vectorizer = tf.keras.layers.TextVectorization(
    max_tokens=max_vocab_size,
    output_mode="int",
    output_sequence_length=6  # pad/truncate
)

# Adapt builds vocabulary
word_vectorizer.adapt(corpus)

# View vocabulary
word_vocab = word_vectorizer.get_vocabulary()
print("Word Vocabulary:")
print(word_vocab)
print("Vocabulary Size:", len(word_vocab))


Word Vocabulary:
['', '[UNK]', 'the', 'text', 'language', 'words', 'tokenization', 'to', 'is', 'subword', 'nlp', 'models', 'can', 'are', 'and', 'performance', 'of', 'in', 'a', 'word']
Vocabulary Size: 20


### Encode Sentences

In [29]:
word_encoded = word_vectorizer(corpus)
print("WOrd-Level Encoded Sequences: ")
print(word_encoded.numpy())

WOrd-Level Encoded Sequences: 
[[ 1  1  1  4  1  0]
 [ 1  1  1  1 14  1]
 [10  8 18  1 16  1]
 [ 6  8  2  1  1 17]
 [ 1  1  1  4  1  0]
 [19  1  1  1  1  0]
 [ 1  1 14  1  1 13]
 [ 2  1  1  1  1 15]
 [ 1  4 11  1  1 16]
 [ 3  1  1  1  1  1]
 [10  1 13  1 17  1]
 [ 1  1  8 18  1 10]
 [ 1  1  1  1  1 17]
 [ 1  1  1  1  1  7]
 [ 1  1  1  3  1  1]
 [ 3  1  1  3  1  1]
 [ 4 11 12  1  1  3]
 [ 1  1 11 12  1 15]
 [ 2  1 16  1 12  1]
 [ 9  6  1  1  1  5]
 [ 1  1  1  8 18  1]
 [ 1  8  1  9  6  1]
 [ 6 12  1  1  1  2]
 [ 2  1  1  1  2 11]
 [ 1  5 13  1  5  1]
 [ 1 14  1 13  1  1]]
